---
- name: "Creates directory"
  file:
    path: /home/ubuntu/backend
    state: directory
    
- name: "Move backend files to remote server."
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: change ownership
  become: true
  shell: chown ubuntu:ubuntu  /home/ubuntu/backend/ -R

- name: "Install dependencies"
  shell: | 
    npm install
  args:
    chdir: /home/ubuntu/backend
    
- name: "build package"
  shell: |
    npm run build
  args:
    chdir: /home/ubuntu/backend

- name: "run server"
  shell: |
    pm2 start npm --name backend -- run start
  args:
    chdir: /home/ubuntu/backend
